context:
  name: certbot-dns-nsone
  version: "5.2.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 61ca726da04e46dfb905d7cc9f980430bd02bee997dac4e3c2b6e68c95551011

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - acme >=${{ version }}
    - certbot >=${{ version }}
    - dns-lexicon >=3.14.1

tests:
  - python:
      imports:
        - certbot_dns_nsone
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://certbot.eff.org
  summary: NS1 DNS Authenticator plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://certbot.eff.org
  repository: https://github.com/certbot/certbot

extra:
  recipe-maintainers:
    - pavelzw
